// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZJ2jpeXSeMKVajVlBQIaN43pxiWqvSOc',
    appId: '1:772114685715:web:8995d2b02b8612040504e6',
    messagingSenderId: '772114685715',
    projectId: 'hackathon-572c3',
    authDomain: 'hackathon-572c3.firebaseapp.com',
    storageBucket: 'hackathon-572c3.firebasestorage.app',
    measurementId: 'G-ZNDJB0W4TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvdRvS0exhmnRGr2YjJNXNlh4pxovPqW0',
    appId: '1:772114685715:android:4b9a1fced2f44aa10504e6',
    messagingSenderId: '772114685715',
    projectId: 'hackathon-572c3',
    storageBucket: 'hackathon-572c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8N1kUXMZjoB3J_2mppeW07Leti-jVaYU',
    appId: '1:772114685715:ios:0f9906f22c00ee580504e6',
    messagingSenderId: '772114685715',
    projectId: 'hackathon-572c3',
    storageBucket: 'hackathon-572c3.firebasestorage.app',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8N1kUXMZjoB3J_2mppeW07Leti-jVaYU',
    appId: '1:772114685715:ios:0f9906f22c00ee580504e6',
    messagingSenderId: '772114685715',
    projectId: 'hackathon-572c3',
    storageBucket: 'hackathon-572c3.firebasestorage.app',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZJ2jpeXSeMKVajVlBQIaN43pxiWqvSOc',
    appId: '1:772114685715:web:f2971c53d9bbda400504e6',
    messagingSenderId: '772114685715',
    projectId: 'hackathon-572c3',
    authDomain: 'hackathon-572c3.firebaseapp.com',
    storageBucket: 'hackathon-572c3.firebasestorage.app',
    measurementId: 'G-DGPN3VS11W',
  );
}
